[package]
name = "mc-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
resolver = "2"
members = [
    "mc-mcp-domain",
    "mc-mcp-application",
    "mc-mcp-infrastructure",
    "mc-mcp-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1"
testcontainers = "0.23"
qdrant-client = "1.13.0"
