[reference]
# Default path is now the system's cache directory (e.g., ~/.cache/mc-mcp on Linux).
# You can uncomment and set a specific path if needed.
# prebuilt_index_path = "artifacts/prebuilt_index.jsonl.gz"

# [[reference.sources]]
# name = "mc-docs"
# source_type = "local"
# path = "metacontract/mc/site/docs"

# [[reference.sources]]
# name = "solidity-docs"
# source_type = "local"
# path = "docs/solidity"

# [[reference.sources]]
# name = "user-docs"
# source_type = "local"
# path = "docs/user"

[scripts]
deploy = "scripts/Deploy.s.sol" # Default deploy script path
# upgrade = "scripts/Upgrade.s.sol" # Example for upgrade script later
